### ISSUE TITLE
what is the difference between the local pretrained model and the roboflow pretrain model?

### ISSUE THREAD

**Issue by jawaechan** [tsugg/LOCO-YOLOv8#1]
Hi, 
   what is the difference between the local pretrained model and the roboflow pretrain model?
   Another, I can not download the pretrained model in roboflow with the given API key and it is shown that 
traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/delta/miniconda3/envs/yolov7/lib/python3.8/site-packages/roboflow/models/object_detection.py", line 478, in download
    r.raise_for_status()
  File "/home/delta/miniconda3/envs/yolov7/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.roboflow.com/tommy-sugg-uhvch/logistics-objects-in-context/1/ptFile?api_key=31VX6QPkOv8zgpPVSVrs

**Comment by tsugg** [comment]
I just wanted to demonstrate that if you didn't want to train a model on your local pc, you could have it done automatically in the cloud. There shouldn't be a difference in the models since they were trained on the same images with the default settings.

I haven't kept up to date with my roboflow account so it might be that the API key expired or something. The command that has all the "!gdown" commands is downloading that local model into the notebook from my google drive. So if you want to use the LOCO trained model, just use that best.pt file that gets downloaded
